INSERT INTO ittraining.formation VALUES ( 1,
	"Formations en informatique",
    "Se former aux principales librairies du langage",
    "4 jours (28 heures)",
    "Formation - Développement Java avancé et accès aux données",
	"2 410,00 €  HT",
	"Java",
	"Langages informatiques",
	"Lille");
INSERT INTO ittraining.formation VALUES (2,
"Formations en informatique",
"Se former aux principales librairies du langage",
"8h45min",
"Certification Développement de sites web dynamiques (option langage PHP)",
"180,00 €  HT",
"Certifications PHP",
"Certifications ENI",
"Paris");
