spring:
  datasource:
    url: jdbc:mysql://localhost:3306/it_training_base_locale?connectionTimeZone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

